# Generated by Django 3.1.7 on 2021-04-21 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGood',
            fields=[
                ('uuid', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('uuid_good', models.CharField(max_length=36)),
                ('ext', models.CharField(blank=True, max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='img/%Y/%m/%d/')),
                ('title', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id_uuid', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('uuid', models.CharField(default='', max_length=36)),
                ('name', models.CharField(default='', max_length=300)),
                ('uuid_parent', models.CharField(blank=True, default='', max_length=36)),
                ('isGroup', models.BooleanField(blank=True, default=False)),
                ('article_number', models.CharField(blank=True, default='', max_length=50)),
                ('uuid_part', models.CharField(blank=True, max_length=36)),
            ],
            options={
                'unique_together': {('uuid', 'uuid_part')},
            },
        ),
    ]
