# Generated by Django 3.1.7 on 2021-03-15 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGood',
            fields=[
                ('uuid', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('uuid_good', models.CharField(max_length=36)),
                ('ext', models.CharField(blank=True, max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='img/%Y/%m/%d/')),
                ('title', models.CharField(blank=True, max_length=120)),
            ],
        ),
    ]
