# Generated by Django 3.1.7 on 2021-04-14 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_good'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='isGroup',
            field=models.BooleanField(default=False),
        ),
    ]
