# Generated by Django 3.1.7 on 2021-04-14 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_good_isgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='article_number',
            field=models.CharField(default='', max_length=50),
        ),
    ]
