# Generated by Django 3.1.7 on 2021-04-14 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210415_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='article_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='good',
            name='isGroup',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='good',
            name='uuid_parent',
            field=models.CharField(blank=True, default='', max_length=36),
        ),
    ]
