# Generated by Django 3.2 on 2021-04-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210415_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='uuid_part',
            field=models.CharField(blank=True, max_length=36),
        ),
    ]
